# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate recent updated

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 101
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Generate README
      run: |
        python readme_gen.py
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_message: "[Bot] Update recent changes"
